/**
 * @file assets/manifest/textures.ts
 * @description Static manifest for all texture assets used in 3D Atlas.
 */

import { type AssetManifestEntry } from '@/engine/assets/AssetManifest'
import { AssetPriority } from '@/engine/assets/AssetPriority'

export const textureManifest: AssetManifestEntry[] = [
  // ── Earth textures ─────────────────────────────────────────────────────
  {
    id: 'texture/earth-diffuse',
    name: 'Earth Diffuse Map',
    category: 'texture',
    path: '/textures/earth_diffuse.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.CRITICAL,
    preload: true,
    cache: true,
    qualityLevel: 'all',
    compression: 'none',
    dependencies: [],
    tags: ['hero', 'scene-01'],
    group: 'earth',
  },
  {
    id: 'texture/earth-normal',
    name: 'Earth Normal Map',
    category: 'texture',
    path: '/textures/earth_normal.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.HIGH,
    preload: false,
    cache: true,
    qualityLevel: 'medium',
    compression: 'none',
    dependencies: ['texture/earth-diffuse'],
    tags: ['hero', 'scene-01'],
    group: 'earth',
  },
  {
    id: 'texture/earth-specular',
    name: 'Earth Specular Map',
    category: 'texture',
    path: '/textures/earth_specular.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.NORMAL,
    preload: false,
    cache: true,
    qualityLevel: 'high',
    compression: 'none',
    dependencies: ['texture/earth-diffuse'],
    tags: ['scene-01'],
    group: 'earth',
  },
  {
    id: 'texture/earth-clouds',
    name: 'Earth Cloud Layer',
    category: 'texture',
    path: '/textures/earth_clouds.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.NORMAL,
    preload: false,
    cache: true,
    qualityLevel: 'medium',
    compression: 'none',
    dependencies: ['texture/earth-diffuse'],
    tags: ['hero', 'scene-01'],
    group: 'earth',
  },

  // ── Particle textures ──────────────────────────────────────────────────
  {
    id: 'texture/particle-dot',
    name: 'Particle Dot',
    category: 'texture',
    path: '/textures/particles/dot.png',
    format: 'png',
    size: 0,
    priority: AssetPriority.HIGH,
    preload: true,
    cache: true,
    qualityLevel: 'all',
    compression: 'none',
    dependencies: [],
    tags: ['hero', 'particles'],
    group: 'particles',
  },
  {
    id: 'texture/particle-glow',
    name: 'Particle Glow',
    category: 'texture',
    path: '/textures/particles/glow.png',
    format: 'png',
    size: 0,
    priority: AssetPriority.NORMAL,
    preload: false,
    cache: true,
    qualityLevel: 'medium',
    compression: 'none',
    dependencies: [],
    tags: ['hero', 'particles'],
    group: 'particles',
  },

  // ── Hero fallback ──────────────────────────────────────────────────────
  {
    id: 'image/hero-fallback',
    name: 'Hero Fallback Image',
    category: 'image',
    path: '/images/hero-fallback.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.CRITICAL,
    preload: true,
    cache: true,
    qualityLevel: 'all',
    compression: 'none',
    dependencies: [],
    tags: ['hero'],
    group: 'hero',
  },
  {
    id: 'image/og-image',
    name: 'OG Image',
    category: 'image',
    path: '/images/og-image.jpg',
    format: 'jpg',
    size: 0,
    priority: AssetPriority.LAZY,
    preload: false,
    cache: false,
    qualityLevel: 'all',
    compression: 'none',
    dependencies: [],
    tags: [],
    group: 'meta',
  },
]
